.include "dirty.mk"

OBJS=index.html \
	impurify-aaron-swartz-is-the-defenseless-dead.html \
	mike-masnick-says-fuck-off.html \
	impurify-did-not-personally-know-aaron-swartz.html \
	mike-masnick-says-i-am-the-dumbest.html \
	impurify-textual-criticism.html \
	mike-masnick-aint-reading.html \
	timeline.html

all: ${OBJS}
