.include "dirty.mk"

all: index.html

SUBDIR=about \
	aaron-swartz

.include <bsd.subdir.mk>

#all:
#	echo ${TEMPLATE}
#	echo "`realpath --relative-to=. ${HOME}/dutr/etc/dutr.css`  `realpath --relative-to=. ${HOME}/dutr/etc/katex-min.css`"
