.include "dirty.mk"

all: index.html

SUBDIR=about \
	aaron-swartz \
	age \
	ai \
	copyright \
	crypto \
	free-speech \
	neology \
	personals

.include <bsd.subdir.mk>

#all:
#	echo ${TEMPLATE}
#	echo "`realpath --relative-to=. ${HOME}/dutr/etc/dutr.css`  `realpath --relative-to=. ${HOME}/dutr/etc/katex-min.css`"
